version: "3.8"
services:
  postgres:
    container_name: node-indexer
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: node_indexer
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./dbschema/schema.sql:/docker-entrypoint-initdb.d/schema.sql # init db schemas on start
    restart: unless-stopped
volumes:
  postgres-data:
