[global]
log_level = 'info'

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[rest]
enabled = true
host = '0.0.0.0'
port = 3000

[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001

[[chains]]
id = 'localoraichain-b'
type = 'CosmosSdk'
rpc_addr = 'http://localoraichain-b:26657'
grpc_addr = 'http://localoraichain-b:9090'
rpc_timeout = '10s'
account_prefix = 'orai'
key_name = 'localoraichain-b'
key_store_type = 'Test'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 4000000
event_source = { mode = 'pull' }
gas_multiplier = 1.5
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '30s'
memo_prefix = ''
sequential_batch_tx = false

[chains.trust_threshold]
numerator = '1'
denominator = '3'

[chains.gas_price]
price = 0.1
denom = 'orai'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-*']]

[chains.address_type]
derivation = 'cosmos'

[[chains]]
id = 'localoraichain-a'
type = 'CosmosSdk'
rpc_addr = 'http://localoraichain-a:26657'
grpc_addr = 'http://localoraichain-a:9090'
rpc_timeout = '10s'
account_prefix = 'orai'
key_name = 'localoraichain-a'
key_store_type = 'Test'
store_prefix = 'ibc'
default_gas = 100000
event_source = { mode = 'pull' }
max_gas = 400000
gas_multiplier = 1.5
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '30s'
memo_prefix = ''
sequential_batch_tx = false

[chains.trust_threshold]
numerator = '1'
denominator = '3'

[chains.gas_price]
price = 0.1
denom = 'orai'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-*']]

[chains.address_type]
derivation = 'cosmos'
