name: Simulations

on:
  pull_request:
  push:
    branches:
      - release/**

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.7"
      - run: make install
  
  test-sim-multi-seed-short:
    runs-on: ubuntu-lastest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.7"
          check-latest: true
      - name: test-sim-multi-seed-short
        run: |
            make test-sim-multi-seed-short